### ISSUE TITLE
Pagekit cli PDOException

### ISSUE THREAD

**Issue by muuknl** [pagekit/pagekit#412]
I just installed pagekit and I absolutely love it. I will definitely try to contribute on the marketplace. However, I do have an error showing up when using the commandline. It gives me the following error:

```
Fatal error: Uncaught exception 'PDOException' with message 'could not find driver' in C:\Users\maart\Documents\Development\Web Applications\pagekit\app\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:43
Stack trace:
#0 C:\Users\maart\Documents\Development\Web Applications\pagekit\app\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'homestead', 'secret', Array)
#1 C:\Users\maart\Documents\Development\Web Applications\pagekit\app\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOMySql\Driver.php(45): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'homestead', 'secret', Array)
#2 C:\Users\maart\Documents\Development\Web Applications\pagekit\app\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'homestead', 'secret', Array)
#3 C:\Users\maart\Documents\Development\Web Applications\pagekit\app\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(814): Doctrine\DBAL\Co in C:\Users\maart\Documents\Development\Web Applications\pagekit\app\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php on line 115
```

The website itself loads perfectly fine, it is just the command line tool.

**Comment by muuknl** [comment]
Ok never mind, it was me being in a different vm.
